name: Fix Dependabot PR

on:
  push:
    branches: [dependabot/npm_and_yarn/**]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          persist-credentials: false # minimize exposure

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Autofix Yarn Dependencies
        run: |
          yarn install

      - name: Config Git
        run: |
          # use personal access token to allow triggering new workflow
          BASIC_AUTH=$(echo -n "x-access-token:${{ secrets.AUTOMERGE_PAT }}" | base64)
          echo "::add-mask::$BASIC_AUTH"
          git config --global user.name '${{ github.event.commits[0].author.name }}'
          git config --global user.email '${{ github.event.commits[0].author.email }}'
          git config --local http.$GITHUB_SERVER_URL/.extraheader "AUTHORIZATION: basic $BASIC_AUTH"

      - name: Commit changes
        shell: bash
        run: |
          git diff-index --quiet HEAD
          result=$?

          set -e
          if [ result == 0 ]
          then
            echo "no changes detected"  
          else
            echo "changes detected"
            git add yarn.lock .yarn/cache .pnp.*
            git commit -m "Dependabot autofix"
            git push
          fi
